### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by coreyjjames** [OTRChat/NodeChat#31]
Hey @joshghent,

I have a bunch of classmate's that are interested in working on this project for a class project.
We would be working quickly over the next 6 week's. So I would either need permissions for this repo, or my class and I can work on my fork then I can send you a 1 big PR after were done.

Let me know what you think.

Thanks!

**Comment by joshghent** [comment]
Wow that's amazing @coreyjjames! I'd love to have all your class mates work on this, would be great! You'd be doing me a massive favor and yourselves! I am happy for the entire project to be rewritten tbh.

I was thinking of doing something with RethinkDB, GoLang on the back and then NextJs on the front. But let me know what you want to do as I will most likely not get time :D I'm happy for you guys to take over managing it if you like. Drop me an email with all the github user names you want adding and we can go from there. I will also configure automatic deployments for Heroku so you guys can see your changes on development and live 👍 The urls will be chat.joshghent.com and chat.dev.joshghent.com

If I can be of any more help, please let me know! 

P.S You are already a member of the organisation - do you have access to everything you need?

**Comment by joshghent** [comment]
@coreyjjames Awesome ok thanks man. I just realise that the goal of this project was to be OTR (off the record) so I guess we should drop the DB stuff. Not sure, take it wherever you want it to go. I'm happy to hand it across to you and your class mates and take a back seat in maintaining it.

There are so many features with whatever you approach you take, if you would like some ideas see below
- chat bots - have integration into github etc or something to post new PR's
- channel support - make it so when goes to the site, they can enter a user name, then a random channel id is generated, this allows them to share the channel with their friend. If a person visits a channel url then they can enter a username and enter the channel. The channel is then destroyed when they both leave
- Encryption - because the emphasis is on encryption, maybe we can allow encryption via gpg?
- Push notifications for new messages
- Message parsing - we already do this for image urls, but allow users to post github urls and then show a short description from the repo, Slack does this really well.
- Allow bold and italic text via * and ** 
- Convert to a PWA to allow users to use the app on their phones

I'm sure there is much more you can think of but maybe that gets you started along with other features we have issues for!

Yes I will get that sorted. When getting the projects setup I can help you with the Procfile which is what Heroku needs to run it.
I can also sort any environment variables that need adding, maybe I can add you as a collaborator for these servers so you can modify them yourself if you like.

I just changed the default permission to write! You should have everything you need now, sorry I did not realise that was the default permission level. I have made you an "Owner" in the organisation tho so you should be able to add your friends, and do anything else I can do! Let me know if you need a hand though

Very excited for this project 👍
