### ISSUE TITLE
Convert nodeChatServer to use ES6 features

### ISSUE THREAD

**Issue by dnguneratne** [OTRChat/NodeChat#50]
This will require configuring something like babel.

**Comment by coreyjjames** [comment]
Lets hold of on this until we figure out a database. since we probably are going to need to redo the server. I am going to close this issue for now. We can look into using ES6 features in the new server.

**Comment by dnguneratne** [comment]
Reading https://github.com/OTRChat/NodeChat/issues/31#issuecomment-436223812 I thought a database was not required for this project. Out of curiosity what would it be used for?

**Comment by coreyjjames** [comment]
@dnguneratne The database will be used to hold user data. Which will allow more advanced functionality like user profile pictures.

**Comment by joshghent** [comment]
@coreyjjames @dnguneratne Yeah the original purpose of this project was to be OTR or off-the-record i.e., no user or message data would be stored, but happy for this to be taken in any direction you wish. I think it would be cool, and keep costs down if it was truly OTR. Solving the problem with no database is an interesting problem. Like storing profile pictures on the user end etc.
The only DB we should ideally use is some kind of local database so that we can push offline messages to the server. Other than that, keep it off the server.
I know whatsapp stores messages until they are delivered to the user, so again, maybe we can do something like that? Take it however you want - just a couple suggestions 👍
